### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iSuslov** [alepee/node-printer#1]
When I try to call Printer.list() I get
TypeError: undefined is not a function
at Function.Printer.list

UPD: something wrong with my meteor installation. I'm trying to wrap it in a package to use with meteor
OK, now it's clear. Meteor uses node v 0.10.36 and child_process does not support `spawnSync` :(

Created for Meteor 
https://github.com/iSuslov/node-printer
https://atmospherejs.com/zuzel/node-printer

**Comment by alepee** [comment]
A better way to communicate with a printer is to use the IPP protocol. My `node-printer` module use a text parser to get updates from `lpq` and `lpstats` binaries. This is not very consistent. You can have a look to https://github.com/alepee/node-ipp-interface. This is a WIP module, but it does not miss much to be complete. Feel free to make a PR on it, I would be happy to help if needed

**Comment by alepee** [comment]
Remove use of `child_process.spawnSync`
