### ISSUE TITLE
Unable to print QRCode.

### ISSUE THREAD

**Issue by jitendra-khatri** [alepee/node-printer#10]
I am using TSC TTP-244 Pro to print QRCode. I have a .prn file which was generated with software. I have used that .prn file's programming code for printing the QRCore code.

If I am printing that using BarTender then My printer printing proper QRCodes. But, If I am using `printer.printText(text); // text : Programming codes were in .prn file with some dynamic data`

I am replacing data as per my requirement for printing different data in QRCodes. But, Printer always printing that codes directly instead of QRCodes.

Printer is always printing the text directly. I have tried the same code from Windows machine (Writing file using QNavigator) and it is printing QRCode as needed

**Comment by alepee** [comment]
Do you have a repository or code sample ?
