### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by mdennyh** [alepee/node-printer#5]
I have some weird issue that sometimes occurred when I try to run printText()with https://github.com/alepee/node-printer/blob/master/printer.js at line 303 

`lpq.stdout.on('data', function(data) {}`

that sometimes give me an error `TypeError: Cannot read property 'on' of undefined` and shuts the node server down. My attempt to localize the problem with `try{}catch()` doesn't work either, it just throws another error 

`Error: spawn lpq EMFILE
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
`

It seems that you have problem with `node-process` or something.

**Comment by alepee** [comment]
It may comes from `spawn` module.

As [specified in node documentation](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) `child_process.spawn` returns an object with a `stdout` method. This is a core module, maybe you could check your nodejs version. **This module has been added in v0.1.90**
